// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VacationHireInc.Data;

namespace VacationHireInc.Data.Migrations
{
    [DbContext(typeof(VacationHireContext))]
    partial class VacationHireContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("VacationHireInc.Data.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("VacationHireInc.Data.Entities.ReceptionCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("FuelLevel")
                        .HasColumnType("numeric");

                    b.Property<int>("ObjectCondition")
                        .HasColumnType("integer");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReservationId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("ReceptionCards");
                });

            modelBuilder.Entity("VacationHireInc.Data.Entities.Reservation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("RentalExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RentalStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("VacationHireInc.Data.Entities.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("integer");

                    b.Property<int>("BodyType")
                        .HasColumnType("integer");

                    b.Property<int>("BrandType")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("NumberOfMiles")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ReservationId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VacationHireInc.Data.Entities.ReceptionCard", b =>
                {
                    b.HasOne("VacationHireInc.Data.Entities.Reservation", "Reservation")
                        .WithOne("ReceptionCard")
                        .HasForeignKey("VacationHireInc.Data.Entities.ReceptionCard", "ReservationId");
                });

            modelBuilder.Entity("VacationHireInc.Data.Entities.Reservation", b =>
                {
                    b.HasOne("VacationHireInc.Data.Entities.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("VacationHireInc.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("VacationHireInc.Data.Entities.Reservation", "Reservation")
                        .WithMany("Vehicles")
                        .HasForeignKey("ReservationId");
                });
#pragma warning restore 612, 618
        }
    }
}
